name: Deploy

on:
  push:
    branches: ["main"] # Corrigido de "branchs" para "branches"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x # Versão mais flexível

      - name: Install .NET Wasm Tools
        run: dotnet workload install wasm-tools

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Publish
        run: |
          # Publica diretamente para a pasta docs
          dotnet publish "Blazor WebAssembly/Blazor WebAssembly.csproj" -c Release -o docs --nologo

          # Cria arquivos essenciais
          touch docs/.nojekyll
          echo '<!DOCTYPE html><html><head><script>sessionStorage.redirect=location.pathname;location.replace("/");</script></head></html>' > docs/404.html

          # Configura CSP
          echo 'Content-Security-Policy: default-src '\''self'\''; style-src '\''self'\'' https://fonts.googleapis.com '\''unsafe-inline'\''; font-src '\''self'\'' https://fonts.gstatic.com;' > docs/_headers

      - name: Verify files
        run: ls -R docs # Verifica a estrutura de arquivos

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs" # Alterado de docs/wwwroot para docs

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
