name: Deploy Blazor to Cloudflare Pages
on:
  push:
    branches: [ "main" ]  # Altere se usar outro branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"  # Ou a versão do seu projeto

      - name: Publish Blazor App
        run: |
          dotnet publish -c Release -o publish
          mv publish/wwwroot/* .

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "OrgaTask-Blazor-WebAssembly"
          directory: "."
